### ISSUE TITLE
Make `jj` a soft requirement

### ISSUE THREAD

**Issue by DustVoice** [DustVoice/DustWSL#2]
Update instructions, reflecting the changes made to the dotfile repo DustVoice/dotfiles@2b059fb81b56e0747d3bf0fdc821d5eb92779438.

Chezmoi works best when it just works with `git`.
I haven't tested integration with `jj` yet.
Therefore, `jj` shouldn't be as prevalent in the doc.

A mention of how to use `jj` with `chezmoi`, should be included, according to he [chezmoi doc section](https://www.chezmoi.io/user-guide/advanced/customize-your-source-directory/#use-a-different-version-control-system-to-git).

If `jj` turns out to be beneficial for the chezmoi setup, include it but mention the optionality.

**Comment by DustVoice** [comment]
As it turns out, `chezmoi cd` works quite nice with nushell, so `jj` is partially usable when utilizing `jj git fetch && jj new main@origin`.

**Comment by DustVoice** [comment]
Wrong it should be `jj git fetch && jj rebase -d main@origin`.

**Comment by DustVoice** [comment]
```toml
[update]
command = "nu"
args = ["-c", "jj git fetch; jj rebase -d main@origin"]
```

**Comment by DustVoice** [comment]
```toml
[cd]
command = "nu"

[update]
command = "nu"
args = ["-c", "jj git fetch; jj rebase -d main@origin"]
```

For full `nu` support
